	<footer>
			<div>
		    <h2>contact info</h2>
		    <p><img src="../assets/img/phone.png"> 0762240069 </p>
		    <p><img src="../assets/img/email.png"> porte-damas@gmail.com </p>
		    </div>
		    <div>
		    <h2>Adresse</h2>
		    <p><img src="../assets/img/adresse.png">15 square yves monnier 35200 Rennes</p>
		    </div>
		    <div>
		    <h2>heures d'ouvertures</h2>
		    <p>Du Mardi au Dimanche
		    	10:00 jusqu'à 22:00
		    	Le Lundi est fermée</p>
		    </div>
		</footer>