<header>
    <img src="asset/img/logo.jpg" alt="logo">
    <nav>
        <ul>
                <li>
                    <a href="index.php?route=Qui-sommes-nous">Qui sommes nous?</a>
                </li>
                <li>
                    <a href="index.php?route=Nos-plats">Nos plats</a>
                </li>
                <li>
                    <a href="index.php?route=Reserver">Reserver</a>
                </li>
                 <li>
                    <a href="index.php?route=Votre-avis">Votre-avis</a>
                </li>
                 <li>
                    <a href="index.php?route=Connexion">Connexion</a>
                </li>
        </ul>
    </nav>
</header>