<main>
		    <h1>Porte de Damas </h1>
		    <article>
		    <p>Qui sommes nous?</p>
		    <p>Nous sommes une famille syrienne qui a décidé de vivre en France après plusieurs déménagements dus à la guerre en Syrie.
		    Nous avons décidé de démarrer notre projet en raison de notre passion pour la cuisine syrienne et la diversité de ses plats.</p>
		    <p>Dans la culture culinaire syrienne, nous n'avons pas l'entrée, le plat principal, etc.
		    Nous mettons tous les plats sur la table et chacun commence comme il préfère.</p>
		    </article>
		</main>	
		